In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
df=pd.read_csv(r"C:\Users\JAY LODHA\web-scraping-project\data\raw\books_scraping_dataset_updated_phase_3.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             1000 non-null   str
 1   Price (Excl Tax)  1000 non-null   str
 2   Price (Incl Tax)  1000 non-null   str
 3   Tax               1000 non-null   str
 4   UPC               1000 non-null   str
 5   Product Type      1000 non-null   str
 6   Num Reviews       1000 non-null   int64
 7   Description       1000 non-null   str
 8   Product Page URL  1000 non-null   str
 9   Availability      1000 non-null   str
 10  Rating            1000 non-null   str
 11  Category          1000 non-null   str
 12  Stock Count       1000 non-null   int64
 13  Scrape Timestamp  1000 non-null   str
dtypes: int64(2), str(12)
memory usage: 109.5 KB

In [3]:
df.describe()
df.head()

,Title,Price (Excl Tax),Price (Incl Tax),Tax,UPC,Product Type,Num Reviews,Description,Product Page URL,Availability,Rating,Category,Stock Count,Scrape Timestamp
0,A Light in the Attic,£51.77,£51.77,£0.00,a897fe39b1053632,Books,0,It's hard to imagine a world without A Light i...,https://books.toscrape.com/catalogue/a-light-i...,In stock (22 available),Three,Poetry,22,2026-06-04T13:52:55
1,Tipping the Velvet,£53.74,£53.74,£0.00,90fa61229261140a,Books,0,"""Erotic and absorbing...Written with starling ...",https://books.toscrape.com/catalogue/tipping-t...,In stock (20 available),One,Historical Fiction,20,2026-06-04T13:52:56
2,Soumission,£50.10,£50.10,£0.00,6957f44c3847a760,Books,0,"Dans une France assez proche de la nôtre, un h...",https://books.toscrape.com/catalogue/soumissio...,In stock (20 available),One,Fiction,20,2026-06-04T13:52:57
3,Sharp Objects,£47.82,£47.82,£0.00,e00eb4fd7b871a48,Books,0,"WICKED above her hipbone, GIRL across her hear...",https://books.toscrape.com/catalogue/sharp-obj...,In stock (20 available),Four,Mystery,20,2026-06-04T13:52:58
4,Sapiens: A Brief History of Humankind,£54.23,£54.23,£0.00,4165285e1663650f,Books,0,From a renowned historian comes a groundbreaki...,https://books.toscrape.com/catalogue/sapiens-a...,In stock (20 available),Five,History,20,2026-06-04T13:52:59

In [4]:
df["Rating"]=df['Rating'].replace(["One","Three","Two","Four","Five"],[1,3,2,4,5],inplace=True).astype(int)

C:\Users\JAY LODHA\AppData\Local\Temp\ipykernel_26928\1956996301.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Rating"]=df['Rating'].replace(["One","Three","Two","Four","Five"],[1,3,2,4,5],inplace=True).astype(int)

In [5]:
df.duplicated().value_counts()

False    1000
Name: count, dtype: int64

In [6]:
df.isnull().value_counts()

Title  Price (Excl Tax)  Price (Incl Tax)  Tax    UPC    Product Type  Num Reviews  Description  Product Page URL  Availability  Rating  Category  Stock Count  Scrape Timestamp
False  False             False             False  False  False         False        False        False             False         False   False     False        False               1000
Name: count, dtype: int64

In [7]:
df['Num Reviews'].value_counts()
df['Tax'].value_counts()
df['Product Type'].value_counts()

Product Type
Books    1000
Name: count, dtype: int64

In [8]:
df['Price (Excl Tax)'] = df['Price (Excl Tax)'].str.replace('£', '').astype(float)
df['Price (Incl Tax)'] = df['Price (Incl Tax)'].str.replace('£', '').astype(float)
df.iloc[:,1:3]

     Price (Excl Tax)  Price (Incl Tax)
0               51.77             51.77
1               53.74             53.74
2               50.10             50.10
3               47.82             47.82
4               54.23             54.23
..                ...               ...
995             55.53             55.53
996             57.06             57.06
997             16.97             16.97
998             53.98             53.98
999             26.08             26.08

[1000 rows x 2 columns]

In [9]:
norm=MinMaxScaler()
df[['Price (Excl Tax)','Price (Incl Tax)','Rating', 'Stock Count']] = norm.fit_transform(df[['Price (Excl Tax)','Price (Incl Tax)','Rating', 'Stock Count']])

In [10]:
df.drop(['Tax','Num Reviews','Product Type'],axis=1,inplace=True)
df.head()

,Title,Price (Excl Tax),Price (Incl Tax),UPC,Description,Product Page URL,Availability,Rating,Category,Stock Count,Scrape Timestamp
0,A Light in the Attic,0.835567,0.835567,a897fe39b1053632,It's hard to imagine a world without A Light i...,https://books.toscrape.com/catalogue/a-light-i...,In stock (22 available),0.50,Poetry,1.000000,2026-06-04T13:52:55
1,Tipping the Velvet,0.874975,0.874975,90fa61229261140a,"""Erotic and absorbing...Written with starling ...",https://books.toscrape.com/catalogue/tipping-t...,In stock (20 available),0.00,Historical Fiction,0.904762,2026-06-04T13:52:56
2,Soumission,0.802160,0.802160,6957f44c3847a760,"Dans une France assez proche de la nôtre, un h...",https://books.toscrape.com/catalogue/soumissio...,In stock (20 available),0.00,Fiction,0.904762,2026-06-04T13:52:57
3,Sharp Objects,0.756551,0.756551,e00eb4fd7b871a48,"WICKED above her hipbone, GIRL across her hear...",https://books.toscrape.com/catalogue/sharp-obj...,In stock (20 available),0.75,Mystery,0.904762,2026-06-04T13:52:58
4,Sapiens: A Brief History of Humankind,0.884777,0.884777,4165285e1663650f,From a renowned historian comes a groundbreaki...,https://books.toscrape.com/catalogue/sapiens-a...,In stock (20 available),1.00,History,0.904762,2026-06-04T13:52:59

In [18]:
df.to_csv(r"C:\Users\JAY LODHA\web-scraping-project\data\processed/books_scraping_data_phase_3.csv", index=False, encoding="utf-8-sig")